server:
  port: 8085

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/hritikchauhan332/micro-config-service.git
          clone-on-start: true